#set_property PACKAGE_PIN V17 [get_ports {data[0]}]
#set_property PACKAGE_PIN V16 [get_ports {data[1]}]
#set_property PACKAGE_PIN W16 [get_ports {data[2]}]
#set_property PACKAGE_PIN W17 [get_ports {data[3]}]
#set_property PACKAGE_PIN W15 [get_ports {data[4]}]
#set_property PACKAGE_PIN V15 [get_ports {data[5]}]
#set_property PACKAGE_PIN W14 [get_ports {data[6]}]
#set_property PACKAGE_PIN W13 [get_ports {data[7]}]
#set_property PACKAGE_PIN V2 [get_ports {data[8]}]
#set_property PACKAGE_PIN T3 [get_ports {data[9]}]
#set_property PACKAGE_PIN T2 [get_ports {data[10]}]
#set_property PACKAGE_PIN R3 [get_ports {data[11]}]
#set_property PACKAGE_PIN W2 [get_ports {data[12]}]
#set_property PACKAGE_PIN U1 [get_ports {data[13]}]
#set_property PACKAGE_PIN T1 [get_ports {data[14]}]
#set_property PACKAGE_PIN R2 [get_ports {data[15]}]
set_property PACKAGE_PIN R2 [get_ports {enable}]
set_property PACKAGE_PIN U18 [get_ports {mode[0]}]
set_property PACKAGE_PIN W19 [get_ports {mode[1]}]
set_property PACKAGE_PIN W5 [get_ports {clk}]
set_property PACKAGE_PIN A18 [get_ports {serial_out}]


set_property PACKAGE_PIN U16 [get_ports {counter[0]}]
set_property PACKAGE_PIN E19 [get_ports {counter[1]}]
set_property PACKAGE_PIN U19 [get_ports {counter[2]}]
set_property PACKAGE_PIN V19 [get_ports {counter[3]}]
set_property PACKAGE_PIN W18 [get_ports {counter[4]}]
set_property PACKAGE_PIN U15 [get_ports {counter[5]}]
set_property PACKAGE_PIN U14 [get_ports {counter[6]}]
set_property PACKAGE_PIN V14 [get_ports {counter[7]}]
set_property PACKAGE_PIN V13 [get_ports {counter[8]}]
set_property PACKAGE_PIN V3 [get_ports {counter[9]}]
set_property PACKAGE_PIN B18 [get_ports {serial_in}]


set_property IOSTANDARD LVCMOS33 [get_ports {clk}]

set_property IOSTANDARD LVCMOS33 [get_ports {counter[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[9]}]
set_property IOSTANDARD LVCMOS33  [get_ports {serial_in}]
set_property IOSTANDARD LVCMOS33  [get_ports {serial_out}]

set_property IOSTANDARD LVCMOS33 [get_ports {mode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {mode[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {enable}]



#set_property IOSTANDARD LVCMOS33 [get_ports {data[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[12]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[13]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[14]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data[15]}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets enable_IBUF]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets enable_IBUF[1]]

