set_property PACKAGE_PIN V17 [get_ports {index[0]}]
set_property PACKAGE_PIN V16 [get_ports {index[1]}]
set_property PACKAGE_PIN W16 [get_ports {index[2]}]
set_property PACKAGE_PIN W17 [get_ports {index[3]}]
set_property PACKAGE_PIN W15 [get_ports {index[4]}]
set_property PACKAGE_PIN V15 [get_ports {index[5]}]
set_property PACKAGE_PIN W14 [get_ports {index[6]}]
set_property PACKAGE_PIN W13 [get_ports {index[7]}]

set_property PACKAGE_PIN W2 [get_ports {data[0]}]
set_property PACKAGE_PIN U1 [get_ports {data[1]}]
set_property PACKAGE_PIN T1 [get_ports {data[2]}]
set_property PACKAGE_PIN R2 [get_ports {data[3]}]

set_property PACKAGE_PIN W5 [get_ports {clk}]

set_property PACKAGE_PIN T18 [get_ports {reset}]

set_property PACKAGE_PIN U16 [get_ports {counter[0]}]
set_property PACKAGE_PIN E19 [get_ports {counter[1]}]
set_property PACKAGE_PIN U19 [get_ports {counter[2]}]
set_property PACKAGE_PIN V19 [get_ports {counter[3]}]
set_property PACKAGE_PIN W18 [get_ports {counter[4]}]
set_property PACKAGE_PIN U15 [get_ports {counter[5]}]
set_property PACKAGE_PIN U14 [get_ports {counter[6]}]
set_property PACKAGE_PIN V14 [get_ports {counter[7]}]
set_property PACKAGE_PIN V13 [get_ports {counter[8]}]
set_property PACKAGE_PIN V3 [get_ports {counter[9]}]
set_property PACKAGE_PIN W3 [get_ports {counter[10]}]
set_property PACKAGE_PIN U3 [get_ports {counter[11]}]
set_property PACKAGE_PIN P3 [get_ports {counter[12]}]
set_property PACKAGE_PIN N3 [get_ports {counter[13]}]
set_property PACKAGE_PIN P1 [get_ports {counter[14]}]
set_property PACKAGE_PIN L1 [get_ports {counter[15]}]

set_property PACKAGE_PIN B18 [get_ports {serial_in}]


set_property PACKAGE_PIN W7 [get_ports {led_out[6]}]                    
set_property PACKAGE_PIN W6 [get_ports {led_out[5]}]  
set_property PACKAGE_PIN U8 [get_ports {led_out[4]}]  
set_property PACKAGE_PIN V8 [get_ports {led_out[3]}]  
set_property PACKAGE_PIN U5 [get_ports {led_out[2]}]  
set_property PACKAGE_PIN V5 [get_ports {led_out[1]}]  
set_property PACKAGE_PIN U7 [get_ports {led_out[0]}]  

set_property PACKAGE_PIN U2 [get_ports {led_activate[0]}] 
set_property PACKAGE_PIN U4 [get_ports {led_activate[1]}]
set_property PACKAGE_PIN V4 [get_ports {led_activate[2]}]
set_property PACKAGE_PIN W4 [get_ports {led_activate[3]}] 

set_property IOSTANDARD LVCMOS33 [get_ports {led_out[6]}]                      
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[5]}]                     
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[4]}]                      
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[3]}]                      
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[2]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[1]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[0]}] 
                    
set_property IOSTANDARD LVCMOS33 [get_ports {led_activate[0]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {led_activate[1]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {led_activate[2]}]                  
set_property IOSTANDARD LVCMOS33 [get_ports {led_activate[3]}]



set_property IOSTANDARD LVCMOS33 [get_ports {clk}]

set_property IOSTANDARD LVCMOS33 [get_ports {counter[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {counter[15]}]

set_property IOSTANDARD LVCMOS33  [get_ports {serial_in}]


set_property IOSTANDARD LVCMOS33 [get_ports {reset}]

set_property IOSTANDARD LVCMOS33 [get_ports {index[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {index[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {index[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {index[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {index[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {index[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {index[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {index[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[3]}]

#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets enable_IBUF]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets enable_IBUF[1]]