# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35ticpg236-1L
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Saurabh/Desktop/samyak/new/project_xd/project_xd.cache/wt [current_project]
set_property parent.project_path C:/Users/Saurabh/Desktop/samyak/new/project_xd/project_xd.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Saurabh/Desktop/samyak/new/project_xd/project_xd.srcs/sources_1/new/Design.vhd
  C:/Users/Saurabh/Desktop/samyak/new/project_xd/project_xd.srcs/sources_1/new/comp.vhd
  C:/Users/Saurabh/Desktop/samyak/new/project_xd/project_xd.srcs/sources_1/new/receive.vhd
  C:/Users/Saurabh/Desktop/samyak/new/project_xd/project_xd.srcs/sources_1/new/main.vhd
}
read_xdc C:/Users/Saurabh/Desktop/samyak/new/project_xd/project_xd.srcs/constrs_1/new/main.xdc
set_property used_in_implementation false [get_files C:/Users/Saurabh/Desktop/samyak/new/project_xd/project_xd.srcs/constrs_1/new/main.xdc]

catch { write_hwdef -file main.hwdef }
synth_design -top main -part xc7a35ticpg236-1L
write_checkpoint -noxdef main.dcp
catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
